baseURL = "https://laweeza.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Louisa Shing"


publishDir = "docs"

# Automatically generate robots.txt
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
  socialIcons = [
    {name = "gmail", url = "mailto:louieshing@gmail.com"},
    {name = "linkedin", url = "https://www.linkedin.com/in/louisa-shing/"},
    {name = "github", url = "https://github.com/Laweeza"},
  ]

  avatarUrl = "/images/profile.png"

  avatarSize = "size-m"

  description = "Software Developer from the Bay Area"

  accentColor = "#2EC4B6"

  metaKeywords = ["louisa", "software", "portfolio", "blog", "hugo"]

[menu]
  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "projects"
    url = "/projects/"
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # Display name
    name = "Projects"
    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2


  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 3

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4

    # We use feather-icons: https://feathericons.com/
