baseURL = "https://laweeza.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Louisa Shing"

# theme as git submodule
theme = "anatole"


publishDir = "docs"

summarylength =10
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
description = """
Louisa Shing
Software Developer from SF
"""

# socialIcons

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/louisa-shing/"


[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/Laweeza"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:louieshing@gmail.com"

[menu]

  [[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    url = "/portfolio/"
    weight = 1

  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 2


  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 3

[[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 4
