baseURL = "https://laweeza.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Louisa Shing"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs"

paginate = 1

[params]
title = "Louisa Shing"
author = "Louisa Shing"
description = "Hi, I am a software engineer. Welcome to my personal site!"
profilePicture = "images/profile.png"
disableKinds = ["taxonomy", "term", "home"]

# socialIcons

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/louisa-shing/"


[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/Laweeza"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:louieshing@gmail.com"

[menu]

  [[menu.main]]
    name = "Portfolio"
    identifier = "home"
    url = "/"
    weight = 100

  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 200


  [[menu.main]]
    name = "Blog"
    identifier = "posts"
    url = "/posts/"
    weight = 300

[[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 400

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"